name: Benchmark tdewolff/minify

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Benchmark tdewolff/minify
        run: |
          go install .
          time minify benchmarks/sample_antd.js -o out
          time minify benchmarks/sample_antd.js > out
