name: NodeJS
# remove the branches conditions:
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Test build from source
        run: |
          npm install -g node-gyp
          npm --prefix bindings/js ci
          npm --prefix bindings/js test

      - name: Install
        run: |
          npm install -g node-gyp
          cd bindings/js
          make

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}.node
          path: bindings/js/prebuilds/*/*.node

  deploy:
    # remove the following if:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - uses: actions/download-artifact@v3
        with:
          path: bindings/js/prebuilds

      - run: npm --prefix bindings/js publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
