name: NodeJS
on:
  push:
    #tags:
    #  - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019, windows-latest]
        node: [18]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Windows enviroment
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1

      - name: Test
        run: |
          npm config set msvs_version 2015 --global
          npm config set python python2.7
          python --version
          npm -v
          npm --prefix bindings/js ci
          ls -la bindings/js/build/Release
          npm --prefix bindings/js test
