name: NodeJS
on:
  push:
    #tags:
    #  - 'v*'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16, 18]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Set Windows environment
        if: matrix.os == 'windows-latest'
        #uses: microsoft/setup-msbuild@v1.0.0
        run:
          echo '::set-env name=GYP_MSVS_VERSION::2015'
          echo '::set-env name=GYP_MSVS_OVERRIDE_PATH::C:\\Dummy'

      - name: Install
        run: npm --prefix bindings/js ci
      #npm config set msvs_version 2017

      #- name: Install
      #  uses: bahmutov/npm-install@v1
      #  with:
      #    working-directory: bindings/js

      - name: Test
        run: npm --prefix bindings/js test
